config/routes.rb
Rails.application.routes.draw do
  resources :terms
  resources :user_occasions
  get '/occassions/new', to: 'occasions#new', as: 'new_occasion'
  get '/occasions/:occasion_id', to: 'occasions#show', as: 'occasion'
  resources :occasions do
    resources :events
  end
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'static#index'

  get '/signin', to: 'sessions#new'
  post '/signin', to: 'sessions#create'
  delete '/signout', to: 'sessions#destroy'

  post '/occasions/:occasion_id/add_friend', to: 'occasions#add_friend', as: 'add_friend'

  post '/occasions/:occasion_id/event/:id/vote', to: 'occasions#vote', as: 'vote'

end

app/models/user.rb
class User < ApplicationRecord
  has_many :user_occasions, dependent: :destroy
  has_many :occasions, through: :user_occasions
  has_many :occasions, foreign_key: 'admin_id'
  has_many :events, foreign_key: 'admin_id'
  has_secure_password

  validates :email, uniqueness: true
  validates :name, :email, :password, :password_confirmation, presence: true
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :verify_user, only: [:new, :create]
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    @user.name = @user.name.downcase
    if @user.save
      session[:user_id] = @user.id
      redirect_to user_path(@user)
    else
      flash[:message] = "Please enter valid information"
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    @user.assign_attributes(user_params)
    @user.name = @user.name.downcase
    if @user.save
      redirect_to user_path(@user)
    else
      flash[:message] = "Please enter valid information"
      render :edit
    end
  end

  def destroy
    @user.destroy
    session.clear
    redirect_to root_path
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  def set_user
    @user = User.find(current_user)
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<h1>Edit User</h1>
<br>
<%= flash[:message] %>
<br>
<%= form_for(@user) do |f| %>
  <%= f.label "Name:" %>
  <%= f.text_field :name %><br>
  <%= f.label "Email:" %>
  <%= f.email_field :email %><br>
  <%= f.label "Password:" %>
  <%= f.password_field :password %><br>
  <%= f.label "Password Confirmation:" %>
  <%= f.password_field :password_confirmation %><br>
  <%= f.submit %>
<% end %>

app/views/users/new.html.erb
<body class="homepage">
  <div class="home_msg">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h2>Sign up!</h1>
      </div>
      <%= flash[:message] %>
      <%= form_for @user, {class: 'form-group'} do |f| %>
      <div class="panel-body">
          <%= f.label "Name: " %>
          <%= f.text_field :name, class: 'form-control'%>
          <%= f.label "E-mail: " %>
          <%= f.email_field :email, class: 'form-control'%>
          <%= f.label "Password: " %>
          <%= f.password_field :password, class: 'form-control'%>
          <%= f.label "Confirm Password: " %>
          <%= f.password_field :password_confirmation, class: 'form-control' %><br>
          <%= f.submit class: "btn btn-primary btn-block" %>
        <% end %><br>
      </div>
    </div>
  </div>
</body>

app/views/users/show.html.erb
<h1>Hello, <%= username %>!</h1>

<ul>
  <li> <%= @user.name %> </li>
  <li> <%= @user.email %> </li>
</ul>

<%= link_to "Edit Profile", edit_user_path  %>
<%= link_to "Delete Account", user_path, method: "DELETE" %>
<%= link_to "Sign Out", signout_path, method: "DELETE" %>