config/routes.rb
Rails.application.routes.draw do
  resources :terms
  resources :user_occasions
  get '/occassions/new', to: 'occasions#new', as: 'new_occasion'
  get '/occasions/:occasion_id', to: 'occasions#show', as: 'occasion'
  resources :occasions do
    resources :events
  end
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'static#index'

  get '/signin', to: 'sessions#new'
  post '/signin', to: 'sessions#create'
  delete '/signout', to: 'sessions#destroy'

  post '/occasions/:occasion_id/add_friend', to: 'occasions#add_friend', as: 'add_friend'

  post '/occasions/:occasion_id/event/:id/vote', to: 'occasions#vote', as: 'vote'

end

app/models/event.rb
class Event < ApplicationRecord
  include ActiveModel::Validations
  belongs_to :occasion
  belongs_to :term
  belongs_to :admin, class_name: 'User'
  has_many :user_events, dependent: :destroy

  validates :name, presence: true
  validates_with TermValidator

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]
  before_action :set_user, only: [:create]
  before_action :set_occasion_check_user, only: [:new, :create]
  before_action :event_admin?, only: [:edit, :update, :destroy]

  def new
    @event = Event.new
  end

  def create
    @event = Event.new(event_params)
    term = Term.find_or_create_by(term_params)
    @event.term = term
    @event.occasion = @occasion
    @event.admin = @user
    if @event.save
      redirect_to occasion_event_path(@occasion, @event)
    else
      flash[:message] = @event.errors.full_messages
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    term = Term.find_or_create_by(term_params)
    @event.term = term
    if @event.update(event_params)
      redirect_to occasion_event_path(@event.occasion, @event)
    else
      flash[:message] = @event.errors.full_messages
      render :edit
    end
  end

  def destroy
    occasion = @event.occasion
    @event.destroy
    redirect_to occasion_path(occasion)
  end

  private

  def event_params
    params.require(:event).permit(:name, :location, :duration)
  end

  def term_params
    params.require(:event).require(:term).permit(:start_term, :end_term)
  end

  def set_event
    @event = Event.find(params[:id])
  end

  def event_admin?
    redirect_to root_path if @event.admin.id != current_user
  end

end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/edit.html.erb
<h1>Edit Event</h1>
<br>
<% if flash[:message] %>
  <ul>
    <% flash[:message].each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>
<br>
<%= form_for [@event.occasion, @event] do |f| %>
  <%= f.label "Name:" %>
  <%= f.text_field :name %><br>
  <%= f.label "Location:" %>
  <%= f.text_field :location %><br>
  <%= f.label "Minimum Duration:" %>
  <%= f.time_field :duration %><br>
  <%= f.fields_for :term, @event.term do |t| %>
    <%= t.label "Start Time:" %>
    <%= t.datetime_field :start_term, min: Date.today %><br>
    <%= t.label "End Time:" %>
    <%= t.datetime_field :end_term, min: Date.today %><br>
  <% end %>
  <%= f.submit %>
<% end %>

app/views/events/new.html.erb
<h1>Create Event</h1>
<% if flash[:message] %>
  <ul>
    <% flash[:message].each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>
<%= form_for [@occasion, @event] do |f| %>
  <%= f.label "Name" %>
  <%= f.text_field :name %><br>
  <%= f.label "Location" %>
  <%= f.text_field :location %><br>
  <%= f.label "Minimum Duration" %>
  <%= f.time_select :duration, minute_step: 30, default: {hour: 1} %><br>
  <%= f.fields_for :term, @event.term do |t| %>
    <%= t.label "Start Time:" %>
    <%= t.datetime_field :start_term, min: Date.today %><br>
    <%= t.label "End Time:" %>
    <%= t.datetime_field :end_term, min: Date.today %><br>
  <% end %>
  <%= f.submit %>
<% end %>

app/views/events/show.html.erb
<h1> <%= @event.name %> </h1>
<ul>
  <li>Location: <%= @event.location %> </li>
  <li>Duration: <%= @event.duration.strftime("%H hr %M min") %> </li>
  <li>Start Time: <%= @event.term.start_term.strftime("%A, %b %d, %Y - %I:%M %P") %> </li>
  <li>End Time: <%= @event.term.end_term.strftime("%A, %b %d, %Y - %I:%M %P") %> </li>
</ul>
<br>
<%= link_to "Back to Occasion", occasion_path(@event.occasion) %><br></br>
<% if @event.admin.id == current_user %>
  <%= link_to "Edit Event", edit_occasion_event_path(@event.occasion, @event) %>
  <%= link_to "Delete Event", occasion_event_path(@event.occasion, @event), method: "DELETE" %>
<% end %>