config/routes.rb
Rails.application.routes.draw do
  resources :terms
  resources :user_occasions
  get '/occassions/new', to: 'occasions#new', as: 'new_occasion'
  get '/occasions/:occasion_id', to: 'occasions#show', as: 'occasion'
  resources :occasions do
    resources :events
  end
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'static#index'

  get '/signin', to: 'sessions#new'
  post '/signin', to: 'sessions#create'
  delete '/signout', to: 'sessions#destroy'

  post '/occasions/:occasion_id/add_friend', to: 'occasions#add_friend', as: 'add_friend'

  post '/occasions/:occasion_id/event/:id/vote', to: 'occasions#vote', as: 'vote'

end

app/models/occasion.rb
class Occasion < ApplicationRecord
  include ActiveModel::Validations
  
  belongs_to :term
  has_many :events, dependent: :destroy
  has_many :user_occasions, dependent: :destroy
  has_many :users, through: :user_occasions
  belongs_to :admin, class_name: 'User'

  validates :title, presence: true
  validates_with TermValidator
end

app/controllers/occasions_controller.rb
require 'byebug'

class OccasionsController < ApplicationController
  helper_method :group_events
  before_action :set_user, only: [:index, :create, :vote]
  before_action :set_occasion, only: [:edit, :update, :destroy]
  before_action :set_occasion_check_user, only: [:show, :vote, :add_friend]
  before_action :occasion_admin?, only: [:edit, :update, :destroy, :add_friend]

  def index
  end

  def new
    @occasion = Occasion.new
  end

  def create
    @occasion = Occasion.new(occasion_params)
    @term = Term.find_or_create_by(term_params)
    @occasion.term = @term
    @occasion.admin = @user
    if @occasion.save
      @user_occasions = UserOccasion.create(user: @user, occasion: @occasion)
      redirect_to occasion_path(@occasion)
    else
      flash[:message] = @occasion.errors.full_messages
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    @term = Term.find_or_create_by(term_params)
    @occasion.term = @term
    if @occasion.update(occasion_params)
      redirect_to occasion_path(@occasion)
    else
      flash[:message] = @occasion.errors.full_messages
      render :edit
    end
  end

  def destroy
    @occasion.destroy
    redirect_to occasions_path
  end

  def add_friend
    @user = User.find_by(name: params[:search].downcase)
    @user_occasion = UserOccasion.find_or_create_by(user: @user, occasion: @occasion)
    flash[:message] = "#{@user.name.capitalize} Added to #{@occasion.title}"
    redirect_to occasion_path(@occasion)
  end



  def vote
    byebug
    @event = Event.find(params[:id])
    @user_occasion = UserOccasion.find_by(user: @user, occasion: @occasion)
    @conflicting_events = group_events.select {|e| e.include?(@event)}.flatten.uniq
    flag = 0
    @conflicting_events.each do |event|
      @vote = UserEvent.find_by(user_occasion: @user_occasion, event: event)
      if @vote.present?
        flag = 1
        break
      end
    end
    @vote = UserEvent.new(user_occasion: @user_occasion) if flag == 0
    @vote.event = @event
    flash[:message] = (@vote.save ? "Vote was recorded" : "Vote was not recorded")
    redirect_to occasion_path(@occasion)
  end

  private

  def group_events
    @sorted_events = sorted_events
    @event_count = @sorted_events.count - 1
    groups = []
    @sorted_events.each_with_index do |event, i|
      count = i + 1
      temp = [event]
      while count <= @event_count
        temp << @sorted_events[count] if event.term.end_term > @sorted_events[count].term.start_term
        count += 1
      end
      if groups.flatten.find {|e| e == temp.last} != nil
      elsif !(temp.count == 1 &&  groups.flatten.find {|e| e == temp.first} != nil)
        groups << temp
      end
    end
    groups
  end

  def occasion_params
    params.require(:occasion).permit(:title)
  end

  def term_params
    params.require(:occasion).require(:term).permit(:start_term, :end_term)
  end

  def sorted_events
    Occasion.find(params[:occasion_id]).events.sort_by {|e| e.term.start_term}
  end

  def set_occasion
    @occasion = Occasion.find(params[:id])
  end

  def occasion_admin?
    redirect_to occasion_path(@occasion) if @occasion.admin.id != current_user
  end

end

app/helpers/occasions_helper.rb
module OccasionsHelper
end

app/views/occasions/edit.html.erb
<h1>Edit Occasion</h1>
<br>
<% if flash[:message] %>
  <ul>
    <% flash[:message].each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>
<br>
<%= form_for(@occasion) do |f| %>
  <%= f.label "Title:" %>
  <%= f.text_field :title %><br>
  <%= f.fields_for :term, @occasion.term do |t| %>
    <%= t.label "Start Time:" %>
    <%= t.datetime_field :start_term, min: Date.today %><br>
    <%= t.label "End Time:" %>
    <%= t.datetime_field :end_term, min: Date.today %><br>
  <% end %>
  <%= f.submit %>
<% end %>

app/views/occasions/index.html.erb
<h1 style="color: turquoise">Occasions</h1>
<br>
<br>
<%= link_to "Create New Occasion", new_occasion_path, class: "btn btn-primary" %>
<br>
<br>
<br>
  <div class="row">

    <% @user.user_occasions.each do |user_occasion| %>
    <div class="col-md-4" style="border-color: darkturquoise; color: darkturquoise">
      <a href="/occasions/<%= user_occasion.occasion.id %>">
      <div class="panel panel-info">
        <img class="img-responsive" src="http://browardschools.com/SiteMedia/SiteResources/icons/PIO/Calendar_Green.png">
        <h4 class="panel-heading"> <%= "#{user_occasion.occasion.title}" %> </h4>
          <ul class="panel-text">
            <% user_occasion.occasion.events.each do |event| %>
              <p><li><%= event.name %></li></p>
            <% end %>
        </ul>
      </div>
      </a>
    </div>
    <% end %>
  </div>

<!-- http://browardschools.com/SiteMedia/SiteResources/icons/PIO/Calendar_Green.png -->
<!-- http://www.racedepartment.com/images/rd_calext/calendar.png -->

app/views/occasions/new.html.erb
<h1>Create New Occasion</h1>
<br>

<% if flash[:message] %>
  <ul>
    <% flash[:message].each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>

<%= form_for(@occasion) do |f| %>
  <%= f.label "Title:" %>
  <%= f.text_field :title %><br>
  <%= f.fields_for :term, @occasion.term do |t| %>
    <%= t.label "Start Time:" %>
    <%= t.datetime_field :start_term, min: Date.today %><br>
    <%= t.label "End Time:" %>
    <%= t.datetime_field :end_term, min: Date.today %><br>
  <% end %>
  <br>
  <%= f.submit %>
<% end %>

app/views/occasions/show.html.erb
<h1>Occasion: <%= @occasion.title %></h1>
<label>Start Time:</label>
<%= @occasion.term.start_term.strftime("%A, %b %d, %Y - %I:%M %P") %><br>
<label>End Time:</label>
<%= @occasion.term.end_term.strftime("%A, %b %d, %Y - %I:%M %P") %>
<br></br>
<% if @occasion.admin.id == current_user %>
  <p>Add a friend:
    <%= form_tag add_friend_path do %>
      <%= text_field_tag :search %>
      <%= submit_tag "Add Friend" %>
    <% end %>
  </p>
  <br>
  <%= link_to "Edit Occasion", edit_occasion_path(@occasion) %>
  <br>
  <%= link_to "Delete Occasion", occasion_path, method: "DELETE" %>
<% end %>
<%= flash[:message] %>
<br>
<%= link_to "Create New Event", new_occasion_event_path(@occasion) %>
<br>

  <% group_events.each do |group| %>
  <ol>
    <% group.each do |event| %>
    <li><%= link_to event.name, occasion_event_path(@occasion, event) %> Votes: <%= event.user_events.count %><br>
      <%= link_to "Vote for this event", vote_path(@occasion, event), method: "POST" %></li>
    <% end %>
  </ol>
  <% end %>
  <h4>Admin:</h4>
  <%= @occasion.admin.name.capitalize %>
  <h4>Friends in Occasion:</h4>
  <% @occasion.users.drop(1).each do |user| %>
  <ul>
    <li> <%= user.name.capitalize %> </li>
  </ul>
  <% end %>