config/routes.rb
Rails.application.routes.draw do
  resources :terms
  resources :user_occasions
  get '/occassions/new', to: 'occasions#new', as: 'new_occasion'
  get '/occasions/:occasion_id', to: 'occasions#show', as: 'occasion'
  resources :occasions do
    resources :events
  end
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'static#index'

  get '/signin', to: 'sessions#new'
  post '/signin', to: 'sessions#create'
  delete '/signout', to: 'sessions#destroy'

  post '/occasions/:occasion_id/add_friend', to: 'occasions#add_friend', as: 'add_friend'

  post '/occasions/:occasion_id/event/:id/vote', to: 'occasions#vote', as: 'vote'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Event Planner</title>
    <link href="//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css" rel="stylesheet"></link>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/1.11.8/semantic.min.css"/>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/1.11.8/semantic.min.js"></script>
    <%= stylesheet_link_tag    "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= analytics_init if Rails.env.production? %>
  </head>
  <body>
    <!--  navbar -->
    <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
        <% if logged_in? %>
          <a class="navbar-brand" href="<%= occasions_path %>"/>Occasions</a>
        <% else %>
          <a class="navbar-brand" href="<%= root_url %>"/>Home</a>
        <% end %>
        </div>
        <div class="navbar-collapse collapse">
           <!--  nav here -->
           <ul class="nav navbar-nav navbar-right">
             <% if logged_in? %>
             <li><a href="/users/<%= current_user %>"> <%= username.capitalize %> </a></li>
              <li><a data-method="delete" href="/signout" rel="nofollow">Log Out</a></li>
            <% end %>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </div>

    <!-- content -->
    <div class="container"  role="main">
      <%= yield %>
    </div>

  </body>
</html>